automation

diff --git a/bin/my-vmctl b/bin/my-vmctl
--- a/bin/my-vmctl
+++ b/bin/my-vmctl
@@ -12,12 +12,15 @@ usage() {
     echo "    install-windows bootrom distro disk mac vmname"
     echo "    run disk mac vmname"
     echo "    list"
+    echo "    list-images"
     echo "    poweroff vmname"
     echo "    destroy vmanme"
+    echo "    destroy-image image"
     echo "    run-linux [ -D grubdev ] [ -g grubdir] [ -G grubconf ] devmap disk mac vmname"
     echo "    run-windows bootrom disk mac vmname"
     echo "    check"
     echo "    connect"
+    echo "    send-script script"
     echo
     echo " special commands (require altroot setup/teardown):"
     echo "    mountalt"
@@ -77,18 +80,6 @@ _do_it() {
 }
 
 
-standard_labels="root swap var tmp work usr data"
-nonshared_mounts="/ /dev /var /tmp /work /usr"
-shared_mounts="/data0 /data1"
-
-
-set -e
-if test -n "$DEBUG"
-then
-    set -x
-fi
-
-
 _is_mounted() {
     if mount -p | awk '{print $2;}' | grep -q "^${1}$"
     then
@@ -145,7 +136,7 @@ _start_ifaces() {
     #    ifconfig bridge0 inet 10.1.2.10 netmask 255.255.255.0
     #    ifconfig bridge0 up
     #fi
-    for i in 0 1 2 3 4 5 6
+    for i in 0 1 2 3 4 5 6 7 8 9
     do
         _tap=`ifconfig tap create`
         ifconfig bridge0 addm ${_tap}
@@ -244,15 +235,16 @@ _install() {
         exit 1
     fi
     mybhyve_opts="$mybhyve_opts -A"
+    _tap=`_pick_tap`
+    #_tap=`_new_tap`
     echo "distro: ${_distro}"
     echo "disk: ${_disk}"
+    echo "tap: ${_tap}"
     echo "mac: ${_mac}"
     echo "vmname: ${_vmname}"
     read -p "Continue? [y/N]> " _answer
     if test "${_answer}" = "y"
     then
-        _tap=`_pick_tap`
-        #_tap=`_new_tap`
         _do_it "my-bhyve $mybhyve_opts -N '${_tap},mac=${_mac}' -I ${_distro} -d ${_disk} ${_vmname}"
         #_destroy_tap ${_tap}
     else
@@ -296,11 +288,14 @@ _install_linux() {
         echo "${_vmname} is in use"
         exit 1
     fi
+    _tap=`_pick_tap`
+    #_tap=`_new_tap`
     echo "grubdev: ${_grubdev}"
     echo "grubconf: ${_grubconf}"
     echo "devmap: ${_devmap}"
     echo "distro: ${_distro}"
     echo "disk: ${_disk}"
+    echo "tap: ${_tap}"
     echo "mac: ${_mac}"
     echo "vmname: ${_vmname}"
     read -p "Continue? [y/N]> " _answer
@@ -310,8 +305,6 @@ _install_linux() {
         then
             mybhyve_opts="${mybhyve_opts} -G ${_grubconf}"
         fi
-        _tap=`_pick_tap`
-        #_tap=`_new_tap`
         _do_it "my-bhyve $mybhyve_opts  -D ${_grubdev} -g ${_grubdir} -L ${_devmap} -I ${_distro} -d ${_disk} -N '${_tap},mac=${_mac}' ${_vmname}"
         #_destroy_tap ${_tap}
     else
@@ -358,16 +351,17 @@ _install_windows() {
     mybhyve_opts="${mybhyve_opts} -l bootrom,`_abspath ${_bootrom}`"
     mybhyve_opts="${mybhyve_opts} -E fbuf,${_fbuf}"
 
+    _tap=`_pick_tap`
     echo "bootrom: ${_bootrom}"
     echo "distro: ${_distro}"
     echo "disk: ${_disk}"
+    echo "tap: ${_tap}"
     echo "mac: ${_mac}"
     echo "fbuf: ${_fbuf}"
     echo "vmname: ${_vmname}"
     read -p "Continue? [y/N]> " _answer
     if test "${_answer}" = "y"
     then
-        _tap=`_pick_tap`
         _do_it "my-bhyve $mybhyve_opts -I ${_distro} -d ${_disk} -N '${_tap},mac=${_mac}' ${_vmname}"
     else
         echo "Exiting ..."
@@ -409,14 +403,15 @@ _run() {
         echo "console: $cdev"
     fi
     mybhyve_opts="$mybhyve_opts -A"
+    _tap=`_pick_tap`
+    #_tap=`_new_tap`
     echo "disk: ${_disk}"
+    echo "tap: ${_tap}"
     echo "mac: ${_mac}"
     echo "vmname: ${_vmname}"
     read -p "Continue? [y/N]> " _answer
     if test "${_answer}" = "y"
     then
-        _tap=`_pick_tap`
-        #_tap=`_new_tap`
         _do_it "my-bhyve $mybhyve_opts -N '${_tap},mac=${_mac}' -d ${_disk} ${_vmname}"
         #_destroy_tap ${_tap}
     else
@@ -464,9 +459,12 @@ _run_linux() {
         mybhyve_opts="$mybhyve_opts -c $cdev"
         echo "console: $cdev"
     fi
+    _tap=`_pick_tap`
+    #_tap=`_new_tap`
     echo "grubconf: ${_grubconf}"
     echo "devmap: ${_devmap}"
     echo "disk: ${_disk}"
+    echo "tap: ${_tap}"
     echo "mac: ${_mac}"
     echo "vmname: ${_vmname}"
     read -p "Continue? [y/N]> " _answer
@@ -476,8 +474,6 @@ _run_linux() {
         then
             mybhyve_opts="${mybhyve_opts} -G ${_grubconf}"
         fi
-        _tap=`_pick_tap`
-        #_tap=`_new_tap`
         _do_it "my-bhyve $mybhyve_opts -N '${_tap},mac=${_mac}' -D hd0,msdos1 -L ${_devmap} -d ${_disk} ${_vmname}"
         #_destroy_tap ${_tap}
     else
@@ -529,16 +525,17 @@ _run_windows() {
     mybhyve_opts="${mybhyve_opts} -l bootrom,`_abspath ${_bootrom}`"
     mybhyve_opts="${mybhyve_opts} -E fbuf,${_fbuf}"
 
+    _tap=`_pick_tap`
     echo "bootrom: ${_bootrom}"
     echo "distro: ${_distro}"
     echo "disk: ${_disk}"
+    echo "tap: ${_tap}"
     echo "mac: ${_mac}"
     echo "fbuf: ${_fbuf}"
     echo "vmname: ${_vmname}"
     read -p "Continue? [y/N]> " _answer
     if test "${_answer}" = "y"
     then
-        _tap=`_pick_tap`
         _do_it "my-bhyve $mybhyve_opts -N '${_tap},mac=${_mac}' -I ${_distro} -d ${_disk} ${_vmname}"
     else
         echo "Exiting ..."
@@ -592,13 +589,21 @@ _runalt() {
     #_destroy_tap ${_tap}
 }
 
+
 _destroy() {
     _do_it "bhyvectl --vm=$1 --destroy"
     return 0
 }
 
-_umountalt() {
 
+_destroy_image() {
+    batch=
+    _do_it "zfs destroy $1"
+    return 0
+}
+
+
+_umountalt() {
     if ! _checkfstat
     then
         echo
@@ -618,6 +623,7 @@ _umountalt() {
     swapoff /dev/gpt/swap${altrootnum}
 }
 
+
 _mountalt() {
     for i in $nonshared_mounts
     do
@@ -636,6 +642,7 @@ _mountalt() {
     altrootnum=`_rootdev | sed 's|.*/root||'`
     swapon /dev/gpt/swap${altrootnum}
 }
+
 
 _linkalt() {
     local _arg altrootdev
@@ -663,6 +670,47 @@ _linkalt() {
         exit 1
     fi
 }
+
+_send_script() {
+    local _cdev _prompt _line
+    _cdev=$1
+    _prompt="`basename $_cdev`:>"
+    while true
+    do
+        read _line
+        if echo "$_line" | grep ^__secure__: >/dev/null 2>&1
+        then
+            _line=`echo "$_line" | sed -e 's/^__secure__://'`
+            echo "$_prompt ***"
+        else
+            echo "$_prompt $_line"
+        fi
+        if echo "$_line" | grep '^#' >/dev/null 2>&1
+        then
+            continue
+        fi
+        printf "$_line\n" >$_cdev
+        if test -z "$_line"
+        then
+            break
+        fi
+        sleep 0.2
+    done
+}
+
+
+# main
+#
+standard_labels="root swap var tmp work usr data"
+nonshared_mounts="/ /dev /var /tmp /work /usr"
+shared_mounts="/data0 /data1"
+
+set -e
+if test -n "$DEBUG"
+then
+    set -x
+fi
+
 
 batch=1
 dryrun=
@@ -778,6 +826,10 @@ elif test "$1" = "list"
 then
     pgrep -lf bhyve: | awk '{print $3;}'
 
+elif test "$1" = "list-images"
+then
+    zfs list -t volume
+
 elif test "$1" = "poweroff"
 then
     if test -n "$2" && ls /dev/vmm | grep -q "$2"
@@ -792,6 +844,10 @@ then
 elif test "$1" = "destroy"
 then
     _destroy $2
+
+elif test "$1" = "destroy-image"
+then
+    _destroy_image $2
 
 elif test "$1" = "run-linux"
 then
@@ -917,6 +973,27 @@ then
     then
         echo "Connecting to $cdev ..."
         cu -l $cdev -t
+    else
+        echo "Could not find console $cdev"
+        exit 1
+    fi
+
+elif test "$1" = "send-script"
+then
+    if test -z "$2"
+    then
+        cdev="/dev/nmdm0B"
+    else
+        cdev="/dev/nmdm${2}B"
+    fi
+    if test -e $cdev
+    then
+        echo "Sending $3 to $cdev ..."
+        if test -e "$3"
+        then
+            cat $3 | _send_script $cdev
+        fi
+
     else
         echo "Could not find console $cdev"
         exit 1
diff --git a/share/my-vmctl-preset-subr b/share/my-vmctl-preset-subr
--- a/share/my-vmctl-preset-subr
+++ b/share/my-vmctl-preset-subr
@@ -1,15 +1,26 @@
+#!/bin/sh
+
+required () {
+    set -e
+    for i in $*
+    do
+        eval "test -n \"\$$i\"" || ( echo missing \$$i && false )
+    done
+    set +e
+}
+
+
 newvol () {
-    local _vol _name _size
+    local _dataset _vol _name _size
     _name=$1
     _size=$2
-    if test -n "$_my_vm_ctl_ddev_zfs"
+    _vol=$D/$_name
+    if test -n "$_zfs"
     then
-        _vol=skyrta/$_name
-        zfs destroy $_vol
-        zfs create -V $_size $_vol
-        _vol=/dev/zvol/$_vol
+        _dataset=$P/$_name
+        zfs destroy $_dataset
+        zfs create -V $_size $_dataset
     else
-        _vol=$_name
         rm -f $_vol && truncate -s $_size $_vol
     fi
     echo $_vol
@@ -18,76 +29,99 @@ newvol () {
 getvol () {
     local _vol _name
     _name=$1
-    if test -n "$_my_vm_ctl_ddev_zfs"
-    then
-        _vol=/dev/zvol/skyrta/$_name
-    else
-        _vol=$_name
-    fi
+    _vol=$D/$_name
     echo $_vol
 }
 
+getdataset () {
+    local _dataset _name
+    _name=$1
+    _dataset=$P/$_name
+    echo $_dataset
+}
+
 run_simple_linux_preset () {
-    local cmd g ddev
+    local _cmd _d _g _ddev _devmapi _devmapr
+
+    required idx tag
+
     my-vmctl destroy $name
+
+    _devmapi=device.map-${id}.install
+    _devmapr=device.map-${id}.run
+
+    cat > device.map-${id}.install <<EOD
+(cd0) $R/${iso}
+(hd0) $D/${disk}
+EOD
+
+    cat > device.map-${id}.run <<EOD
+(cd0) /fake
+(hd0) $D/${disk}
+EOD
+
+
     if test "$1" = "install"
     then
-        cmd=install-linux
-        ddev=`newvol $disk $size`
-        #rm -f $disk && truncate -s $size $disk
+        _cmd=install-linux
+        _ddev=`newvol $disk $size`
         if test -n "$grubi"
         then
-            g="-G $grubi"
+            _g="-G $grubi"
         else
-            g=
+            _g=
         fi
-        d=$devmapi
+        _d=$_devmapi
     else
-        cmd=run-linux
-        ddev=`getvol $disk`
+        _cmd=run-linux
+        _ddev=`getvol $disk`
         if test -n "$grubr"
         then
-            g="-G $grubr"
+            _g="-G $grubr"
         else
-            g=
+            _g=
         fi
-        d=$devmapr
+        _d=$_devmapr
         iso=
     fi
 
-    #my-vmctl -P0:$cpu $cmd $g $d $iso $ddev $mac $name $cdev
-    my-vmctl -M1 $cmd $g $d $iso $ddev $mac $name $cdev
+    #my-vmctl -P0:$cpu $_cmd $_g $_d $iso $_ddev $mac $name $cdev
+    my-vmctl -M1 $_cmd $_g $_d $iso $_ddev $mac $name $cdev
 }
 
 run_simple_freebsd_preset () {
-    local cmd g ddev
+    local _cmd _ddev
+
+    required idx tag
+
     my-vmctl destroy $name
     if test "$1" = "install"
     then
-        cmd=install
-        ddev=`newvol $disk $size`
-        #rm -f $disk && truncate -s $size $disk
+        _cmd=install
+        _ddev=`newvol $disk $size`
     else
-        cmd=run
-        ddev=`getvol $disk`
+        _cmd=run
+        _ddev=`getvol $disk`
         iso=
     fi
 
-    #my-vmctl -P0:$cpu $cmd $iso $ddev $mac $name $cdev
-    my-vmctl -M1 $cmd $iso $ddev $mac $name $cdev
+    #my-vmctl -P0:$cpu $_cmd $iso $_ddev $mac $name $cdev
+    my-vmctl -M1 $_cmd $iso $_ddev $mac $name $cdev
 }
 
 run_simple_windows_preset () {
-    local cmd g ddev
+    local _cmd _ddev
+
+    required idx tag
+
     my-vmctl destroy $name
     if test "$1" = "install"
     then
-        cmd=install-windows
-        ddev=`newvol $disk $size`
-        #rm -f $disk && truncate -s $size $disk
+        _cmd=install-windows
+        _ddev=`newvol $disk $size`
     else
-        cmd=run-windows
-        ddev=`newvol $disk $size`
+        _cmd=run-windows
+        _ddev=`newvol $disk $size`
         if test -z "$fakeiso"
         then
             fakeiso=.fakeiso-$name
@@ -98,17 +132,118 @@ run_simple_windows_preset () {
 
     export DEBUG=yes
 
-    #my-vmctl -P0:$cpu $cmd $bootrom $iso $ddev $mac $name 
-    my-vmctl -M1 $cmd $bootrom $iso $ddev $mac $name 
+    #my-vmctl -P0:$cpu $_cmd $bootrom $iso $_ddev $mac $name 
+    my-vmctl -M1 $_cmd $bootrom $iso $_ddev $mac $name 
 }
 
-#
+
+clone_zfs_dataset () {
+    local _ddevbase _ddev _rootvol _hostname _ip4
+
+    required idx tag mnvm_node_id
+
+    _ddevbase=`getdataset $diskbase`
+    _ddev=`getdataset $disk`
+
+    if ! zfs list "${_ddevbase}" >/dev/null 2>&1
+    then
+        echo "Invalid snapshot ${_ddevbase}"
+        exit 1
+    fi
+    if zfs list "${_ddev}" >/dev/null 2>&1
+    then
+        if test -z "$force"
+        then
+            echo "Already exists ${_ddev}. Set force=1 in the preset file or run my-vmctl destroy-image ${_ddev}"
+            exit 1
+        else
+            zfs destroy ${_ddev}
+        fi
+    fi
+    zfs clone ${_ddevbase} ${_ddev}
+}
+
+
+configure_freebsd () {
+    local _vol _rootvol
+
+    required disk mnvm_node_id
+
+    _vol=`getvol $disk`
+    _rootvol="${_vol}s1a"
+    if test -c ${_rootvol}
+    then
+        mount $_rootvol /mnt
+        sed -E -e "s/^mnvm_node_id=.*$/mnvm_node_id=$mnvm_node_id/" -i.bak /mnt/etc/rc.conf
+        umount /mnt
+    fi
+}
+
+
+configure_linux_ubuntu () {
+    local _passwd
+    required mnvm_node_id cdev
+
+    stty -echo
+    read -p "Password: " _passwd
+    stty echo
+    sed -e \
+        "s/^mnvm_node_id=.*$/mnvm_node_id=$mnvm_node_id/" \
+        -e "s/^__secure__:password$/__secure__:$_passwd/" \
+            <my-vmctl-preset-config-ubuntu \
+            > .my-vmctl-preset-config-ubuntu-tmp
+    my-vmctl send-script $cdev .my-vmctl-preset-config-ubuntu-tmp
+    rm .my-vmctl-preset-config-ubuntu-tmp
+}
+
+
+clone_freebsd_preset () {
+    set -e
+    clone_zfs_dataset
+    configure_freebsd
+}
+
+
+clone_linux_preset () {
+    set -e
+    clone_zfs_dataset
+}
+
+
+# main
+
+_zfs=
+# pool: for zfs hosting
+P=
+# root dir: for ISO images
+R=
+# dev dir: for disk devices
+D=
 if zpool list >/dev/null 2>&1
 then
     if test -z "$MY_VMCTL_DDEV_UFS"
     then
-        _my_vm_ctl_ddev_zfs=1
+        _zfs=1
+        # my pear. hosting
+        P=skyrta
+        R=/$P/vm
+        D=/dev/zvol/$P
+    else
+        R="`pwd`"
+        D="`pwd`"
     fi
 fi
-export _my_vm_ctl_ddev_zfs
 
+# Required variables:
+#   idx, ordinal number
+#   tag, base/template image name like ubuntu-pear-16 or freebsd-pear-11
+cdev="$idx"
+midx=`printf "%02x" $idx`
+idbase=${idbase:-${tag}@base}
+id=${tag}.${midx}
+name=vm-${id}
+size=32G
+cpu=$idx
+mac=58:9c:fc:ea:00:$midx
+disk=.diskdev-${id}
+diskbase=.diskdev-${idbase}
